import { handleUpdate } from "./utils/activity"

const settings = Presence.Settings({
  privacy: {
    type: "boolean",
    default: false,
    label: {
      "en-US": "Privacy mode",
      "fr-FR": "Mode privé",
      "es-ES": "Modo privado",
      "de-DE": "Datenschutzmodus",
      "el-GR": "Λειτουργία απορρήτου",
      "ja-JP": "プライバシーモード",
      "ko-KR": "개인정보 보호 모드",
      "ms-MY": "Mod privasi",
      "pl-PL": "Tryb prywatny",
      "pt-BR": "Modo de privacidade",
      "tr-TR": "Gizlilik modu",
    },
    description: {
      "en-US": "Hide every detail about the content you're watching.",
      "fr-FR": "Masque tous les détails du contenu que vous regardez.",
      "es-ES": "Oculta todos los detalles del contenido que estás viendo.",
      "de-DE": "Alle Details zu den Inhalten ausblenden, die du gerade ansiehst.",
      "el-GR": "Απόκρυψη όλων των λεπτομερειών σχετικά με το περιεχόμενο που παρακολουθείτε.",
      "ja-JP": "視聴中のコンテンツに関するすべての詳細を非表示にします。",
      "ko-KR": "시청 중인 콘텐츠에 관한 모든 세부 정보를 숨깁니다.",
      "ms-MY": "Sembunyikan semua butiran tentang kandungan yang sedang anda tonton.",
      "pl-PL": "Ukryj wszystkie szczegóły oglądanych treści.",
      "pt-BR": "Ocultar todos os detalhes sobre o conteúdo que você está assistindo.",
      "tr-TR": "İzlediğin içerikle ilgili tüm ayrıntıları gizle.",
    },
  },
  showMediaTitle: {
    type: "boolean",
    default: false,
    label: {
      "en-US": "Show media title in activity name",
      "fr-FR": "Afficher le titre du média dans le nom de l'activité",
      "es-ES": "Mostrar el título del contenido en el nombre de la actividad",
      "de-DE": "Medientitel als Aktivitätsnamen anzeigen",
      "el-GR": "Εμφάνιση τίτλου πολυμέσου στο όνομα δραστηριότητας",
      "ja-JP": "アクティビティ名にメディアタイトルを表示",
      "ko-KR": "활동 이름에 미디어 제목 표시",
      "ms-MY": "Paparkan tajuk media sebagai nama aktiviti",
      "pl-PL": "Pokazuj tytuł materiału jako nazwę aktywności",
      "pt-BR": "Mostrar o título da mídia no nome da atividade",
      "tr-TR": "Etkinlik adında medya başlığını göster",
    },
    description: {
      "en-US": "When enabled, use the current media title as the Discord activity name instead of the service name.",
      "fr-FR": "Lorsque cette option est activée, le titre du média en cours remplace le nom du service dans votre activité Discord.",
      "es-ES": "Si está activada, el título del contenido actual sustituye al nombre del servicio en tu actividad de Discord.",
      "de-DE": "Wenn diese Option aktiviert ist, ersetzt der aktuelle Medientitel den Dienstnamen in deiner Discord-Aktivität.",
      "el-GR": "Όταν είναι ενεργό, ο τρέχων τίτλος πολυμέσου αντικαθιστά το όνομα της υπηρεσίας στη δραστηριότητά σου στο Discord.",
      "ja-JP": "有効にすると、Discordのアクティビティ名にサービス名の代わりに再生中のメディアタイトルを表示します。",
      "ko-KR": "활성화하면 Discord 활동 이름에 서비스 이름 대신 현재 미디어 제목을 표시합니다.",
      "ms-MY": "Apabila diaktifkan, tajuk media semasa menggantikan nama perkhidmatan dalam aktiviti Discord anda.",
      "pl-PL": "Po włączeniu tytuł odtwarzanego materiału zastąpi nazwę usługi w Twojej aktywności Discord.",
      "pt-BR": "Quando ativado, o título da mídia atual substitui o nome do serviço na sua atividade do Discord.",
      "tr-TR": "Etkinleştirildiğinde, Discord etkinliğinde hizmet adı yerine oynatılan medyanın başlığı gösterilir.",
    },
  },
  showButtons: {
    type: "boolean",
    default: true,
    label: {
      "en-US": "Show buttons",
      "fr-FR": "Afficher les boutons",
      "es-ES": "Mostrar botones",
      "de-DE": "Schaltflächen anzeigen",
      "el-GR": "Εμφάνιση κουμπιών",
      "ja-JP": "ボタンを表示",
      "ko-KR": "버튼 표시",
      "ms-MY": "Tunjukkan butang",
      "pl-PL": "Pokazuj przyciski",
      "pt-BR": "Mostrar botões",
      "tr-TR": "Düğmeleri göster",
    },
    description: {
      "en-US": "Show action buttons (view video, view profile) on your Discord presence.",
      "fr-FR": "Affiche les boutons d'action (voir la vidéo, voir le profil) sur votre présence Discord.",
      "es-ES": "Muestra botones de acción (ver vídeo, ver perfil) en tu presencia de Discord.",
      "de-DE": "Aktionsschaltflächen (Video ansehen, Profil ansehen) in deiner Discord-Aktivität anzeigen.",
      "el-GR": "Εμφάνιση κουμπιών ενεργειών (προβολή βίντεο, προβολή προφίλ) στην παρουσία σας στο Discord.",
      "ja-JP": "Discordのプレゼンスにアクションボタン（動画を見る、プロフィールを見る）を表示します。",
      "ko-KR": "Discord 프레즌스에 작업 버튼(동영상 보기, 프로필 보기)을 표시합니다.",
      "ms-MY": "Tunjukkan butang tindakan (lihat video, lihat profil) pada kehadiran Discord anda.",
      "pl-PL": "Pokaż przyciski działań (wyświetlanie filmu i profilu) w swojej aktywności na Discordzie.",
      "pt-BR": "Mostrar botões de ação (ver vídeo, ver perfil) na sua presença do Discord.",
      "tr-TR": "Discord etkinliğinde işlem düğmelerini (videoyu görüntüle, profili görüntüle) göster.",
    },
  },
  showProfileUsernames: {
    type: "boolean",
    default: true,
    label: {
      "en-US": "Show profile info",
      "fr-FR": "Afficher les infos du profil",
      "es-ES": "Mostrar información del perfil",
      "de-DE": "Profilinformationen anzeigen",
      "el-GR": "Εμφάνιση πληροφοριών προφίλ",
      "ja-JP": "プロフィール情報を表示",
      "ko-KR": "프로필 정보 표시",
      "ms-MY": "Tunjukkan maklumat profil",
      "pl-PL": "Pokazuj informacje o profilu",
      "pt-BR": "Mostrar informações do perfil",
      "tr-TR": "Profil bilgilerini göster",
    },
    description: {
      "en-US": "Show usernames when you browse profiles.",
      "fr-FR": "Affiche les identifiants lorsque vous consultez des profils.",
      "es-ES": "Muestra los nombres de usuario al explorar perfiles.",
      "de-DE": "Zeige Benutzernamen beim Durchsuchen von Profilen.",
      "el-GR": "Εμφάνιση ονομάτων χρήστη κατά την περιήγηση σε προφίλ.",
      "ja-JP": "プロフィール閲覧時にユーザー名を表示します。",
      "ko-KR": "프로필을 탐색할 때 사용자 이름을 표시합니다.",
      "ms-MY": "Tunjukkan nama pengguna semasa anda melayari profil.",
      "pl-PL": "Pokazuj nazwy użytkowników podczas przeglądania profili.",
      "pt-BR": "Mostrar nomes de usuário ao navegar por perfis.",
      "tr-TR": "Profillere göz atarken kullanıcı adlarını göster.",
    },
  },
})

const presence = new Presence(settings)

presence.on("UpdateData", async (ctx) => handleUpdate(presence, ctx))
